### ISSUE TITLE
fab gh_pages rejects updates

### ISSUE THREAD

**Issue by moorepants** [moorepants/eng122#1]
`fab gh_pages` should handle to people pushing to the gh_pages branch seamlessly, but it seems like it doesn't. It should just force commit on top of that branch and not worry about merging.

**Comment by ixjlyons** [comment]
So just adding a `--force` should do it then? I have to admit I don't know what sensible conditions require a force push to the `gh_pages` branch, but I've had to do it for my personal site a couple times (which is embarrassing since I'm the only one working on that repo).

**Comment by moorepants** [comment]
Using doctr now, no longer relevant.
